// Generated by scripts/gen-email-buttons.mjs — do not edit.
export const EMAIL_BUTTON_SIZES: Record<string, { slug: string; width: number; height: number }> = {
  "Confirmă adresa": {
    "slug": "confirma-adresa",
    "width": 166,
    "height": 44
  },
  "Confirm my email": {
    "slug": "confirm-my-email",
    "width": 174,
    "height": 44
  },
  "Alege parola nouă": {
    "slug": "alege-parola-noua",
    "width": 176,
    "height": 44
  },
  "Choose a new password": {
    "slug": "choose-a-new-password",
    "width": 222,
    "height": 44
  },
  "Confirmă schimbarea": {
    "slug": "confirma-schimbarea",
    "width": 202,
    "height": 44
  },
  "Confirm the change": {
    "slug": "confirm-the-change",
    "width": 189,
    "height": 44
  },
  "Acceptă invitația": {
    "slug": "accepta-invitatia",
    "width": 170,
    "height": 44
  },
  "Accept the invitation": {
    "slug": "accept-the-invitation",
    "width": 198,
    "height": 44
  },
  "Deschide Abonament": {
    "slug": "deschide-abonament",
    "width": 201,
    "height": 44
  },
  "Open Subscription": {
    "slug": "open-subscription",
    "width": 179,
    "height": 44
  },
  "Vezi chitanța": {
    "slug": "vezi-chitanta",
    "width": 141,
    "height": 44
  },
  "See the receipt": {
    "slug": "see-the-receipt",
    "width": 156,
    "height": 44
  },
  "Activează abonamentul": {
    "slug": "activeaza-abonamentul",
    "width": 219,
    "height": 44
  },
  "Activate the subscription": {
    "slug": "activate-the-subscription",
    "width": 229,
    "height": 44
  },
  "Plătește abonamentul": {
    "slug": "plateste-abonamentul",
    "width": 205,
    "height": 44
  },
  "Pay the subscription": {
    "slug": "pay-the-subscription",
    "width": 194,
    "height": 44
  },
  "Deschide Service-Hub": {
    "slug": "deschide-service-hub",
    "width": 208,
    "height": 44
  },
  "Deschide Rapoartele mele": {
    "slug": "deschide-rapoartele-mele",
    "width": 236,
    "height": 44
  },
  "Open My reports": {
    "slug": "open-my-reports",
    "width": 167,
    "height": 44
  }
};
