import { createElement } from 'react';
import type { ServiceIconName } from '../lib/serviceIcons';
import {
  Activity,
  Battery,
  BatteryCharging,
  CircleDot,
  ClipboardCheck,
  Cog,
  Compass,
  Disc,
  Droplet,
  Eye,
  Filter,
  Flame,
  Fuel,
  Gauge,
  Hammer,
  Key,
  Layers,
  LifeBuoy,
  Lightbulb,
  MoreHorizontal,
  Move,
  Package,
  Paintbrush,
  PlugZap,
  Radio,
  ScanLine,
  Settings2,
  Shield,
  Snowflake,
  Sparkles,
  Sun,
  Thermometer,
  Truck,
  Volume2,
  Waves,
  Wind,
  Wrench,
  Zap,
  type LucideIcon,
} from 'lucide-react';

/**
 * The Lucide icons named in the service catalog (`services.icon`, docs/service-catalog.json).
 * Listed one by one so the bundle carries only these; an unknown name falls back to the wrench.
 */
const ICONS: Record<ServiceIconName, LucideIcon> = {
  Activity,
  Battery,
  BatteryCharging,
  CircleDot,
  ClipboardCheck,
  Cog,
  Compass,
  Disc,
  Droplet,
  Eye,
  Filter,
  Flame,
  Fuel,
  Gauge,
  Hammer,
  Key,
  Layers,
  LifeBuoy,
  Lightbulb,
  MoreHorizontal,
  Move,
  Package,
  Paintbrush,
  PlugZap,
  Radio,
  ScanLine,
  Settings2,
  Shield,
  Snowflake,
  Sparkles,
  Sun,
  Thermometer,
  Truck,
  Volume2,
  Waves,
  Wind,
  Wrench,
  Zap,
};

export function ServiceIcon({ name, size = 18, className }: { name: string | null | undefined; size?: number; className?: string }) {
  return createElement((name && ICONS[name as ServiceIconName]) || Wrench, { size, className, 'aria-hidden': true });
}
