// Generates a migration that loads docs/service-catalog.json into service_categories and services.
//
//   node scripts/gen-catalog-sql.ts <migration-file> <schema-version>
//
// Upserts by id, so running it again later (in a new migration) renames and reorders safely.
// It never deletes and never touches `enabled`: services stay valid on old bookings and the
// admin's enable/disable choices (T16b) survive a regeneration.
import { readFileSync, writeFileSync } from 'node:fs';

type Category = { key: string; ro: string; en: string };
type Service = { id: string; category: string; icon: string; ro: string; en: string };
type Catalog = { version: string; categories: Category[]; services: Service[] };

const [outFile, versionArg] = process.argv.slice(2);
const schemaVersion = Number(versionArg);
if (!outFile || !Number.isInteger(schemaVersion) || schemaVersion < 1) {
  console.error('Usage: node scripts/gen-catalog-sql.ts <migration-file> <schema-version>');
  process.exit(1);
}

const catalog = JSON.parse(readFileSync('docs/service-catalog.json', 'utf8')) as Catalog;

const categoryKeys = new Set(catalog.categories.map((c) => c.key));
const serviceIds = new Set<string>();
for (const s of catalog.services) {
  if (!/^[a-z0-9_]+$/.test(s.id)) throw new Error(`Invalid service id: ${s.id}`);
  if (serviceIds.has(s.id)) throw new Error(`Duplicate service id: ${s.id}`);
  if (!categoryKeys.has(s.category)) throw new Error(`Unknown category ${s.category} for ${s.id}`);
  serviceIds.add(s.id);
}

const lit = (value: string) => `'${value.replaceAll("'", "''")}'`;

const categoryRows = catalog.categories
  .map((c, i) => `  (${lit(c.key)}, ${lit(c.ro)}, ${lit(c.en)}, ${i + 1})`)
  .join(',\n');

// Position counts within each category, in file order.
const positions = new Map<string, number>();
const serviceRows = catalog.services
  .map((s) => {
    const position = (positions.get(s.category) ?? 0) + 1;
    positions.set(s.category, position);
    return `  (${lit(s.id)}, ${lit(s.category)}, ${lit(s.icon)}, ${lit(s.ro)}, ${lit(s.en)}, ${position})`;
  })
  .join(',\n');

const sql = `-- Service catalog ${catalog.version}: ${catalog.categories.length} categories, ${catalog.services.length} services.
-- GENERATED by scripts/gen-catalog-sql.ts from docs/service-catalog.json — do not edit by hand.

insert into public.service_categories (key, name_ro, name_en, position)
values
${categoryRows}
on conflict (key) do update
  set name_ro = excluded.name_ro, name_en = excluded.name_en, position = excluded.position;

insert into public.services (id, category_key, icon, name_ro, name_en, position)
values
${serviceRows}
on conflict (id) do update
  set category_key = excluded.category_key, icon = excluded.icon, name_ro = excluded.name_ro,
      name_en = excluded.name_en, position = excluded.position;

update public.schema_version set version = ${schemaVersion};
`;

writeFileSync(outFile, sql);
console.warn(`Wrote ${outFile}: ${catalog.categories.length} categories, ${catalog.services.length} services.`);
